[package]
name = "minikvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build]
target = "aarch64-unknown-linux-gnu"

[dependencies]
sysfs_gpio = "0.6"
ping = "0.4.0"